In [1]:
import pandas as pd
import numpy as np

In [2]:
!sage "../sage_script/combined_sage_script.sage"

filtered knots based on first 2 obstructions, 663 potential ribbon links
[]
[t12054(0,0)(0,0), 10^2_26(0,0)(0,0), L10n32(0,0)(0,0), ooct02_00007(0,0)(0,0), ribbon_2_10_dc42cb6a(0,0)(0,0)]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[]
[]
[t12065(0,0)(0,0), 10^2_98(0,0)(0,0), L10n59(0,0)(0,0), ooct02_00017(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[L12n399(0,0)(0,0), ribbon_2_12_f96042d9(0,0)(0,0)]
[L12n418(0,0)(0,0), ribbon_2_12_b3176713(0,0)(0,0)]
[L12n467(0,0)(0,0)]
[L12n508(0,0)(0,0)]
[L12n520(0,0)(0,0), ribbon_2_14_b82beeeb(0,0)(0,0)]
[L12n529(0,0)(0,0), ribbon_2_12_2522b6b3(0,0)(0,0)]
[L12n544(0,0)(0,0)]
[L12n545(0,0)(0,0)]
[L12n564(0,0)(0,0)]
[L12n817(0,0)(0,0)]
[L12n910(0,0)(0,0), ribbon_2_12_c8af5edd(0,0)(0,0)]
[]
[]
[L12n1109(0,0)(0,0)]
[L12n1180(0,0)(0,0), ribbon_2_12_82049773(0,0)(0,0)]
[L12n1181(0,0)(0,0), ribbon_2_12_318a1895(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L12n1327(0,0)(0,0), ribbon_2_12_4118336d(0,0)(0,0)]
[L12n1333(0,0)(0,0)]
[L12n1375(0,0)(0,0)]
[L12n1755(0,0)(0,0)(0,0)]
[]
[L12n1829(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[t12054(0,0)(0,0), 10^2_26(0,0)(0,0), L10n32(0,0)(0,0), ooct02_00007(0,0)(0,0), ribbon_2_10_dc42cb6a(0,0)(0,0)]
[L13n754(0,0)(0,0), ribbon_2_13_cd58ecfd(0,0)(0,0)]
[L13n759(0,0)(0,0), ribbon_2_13_2b1abc12(0,0)(0,0)]
[L13n760(0,0)(0,0), ribbon_2_13_fc552163(0,0)(0,0)]
[L13n1091(0,0)(0,0), ribbon_2_13_f650d14f(0,0)(0,0)]
[L13n1488(0,0)(0,0), ribbon_2_13_95cfb058(0,0)(0,0)]
[L13n1494(0,0)(0,0), ribbon_2_13_e1b3f674(0,0)(0,0)]
[L13n1627(0,0)(0,0)]
[L13n1704(0,0)(0,0), ribbon_2_13_5a6ca7d0(0,0)(0,0)]
[L13n1707(0,0)(0,0), ribbon_2_13_82f84b7d(0,0)(0,0)]
[L13n1806(0,0)(0,0)]
[L13n1627(0,0)(0,0)]
[L13n1806(0,0)(0,0)]
[L13n2040(0,0)(0,0)]
[L13n2050(0,0)(0,0)]
[L13n2061(0,0)(0,0)]
[L13n2150(0,0)(0,0)]
[L13n2151(0,0)(0,0)]
[L13n2360(0,0)(0,0)]
[L13n2407(0,0)(0,0)]
[L13n2151(0,0)(0,0)]
[L13n2050(0,0)(0,0)]
[L13n2061(0,0)(0,0)]
[L13n2538(0,0)(0,0)]
[L13n3056(0,0)(0,0), ribbon_2_13_5d43499e(0,0)(0,0)]
[]
[]
[L13n4821(0,0)(0,0)]
[]
[]
[]
[]
[]
[L13n5227(0,0)(0,0)]
[]
[]
[L13n5341(0,0)(0,0)]
[]
[]
[]
[]
[]
[L13n5538(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L13n8294(0,0)(0,0)(0,0)]
[L13n8294(0,0)(0,0)(0,0)]
[L13n8396(0,0)(0,0)(0,0)]
[L13n8458(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L13n10965(0,0)(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[L13n11263(0,0)(0,0)(0,0)(0,0), ooct04_00308(0,0)(0,0)(0,0)(0,0)]
[]
[L12n564(0,0)(0,0)]
[L12n544(0,0)(0,0)]
[L12n467(0,0)(0,0)]
[L12n529(0,0)(0,0), ribbon_2_12_2522b6b3(0,0)(0,0)]
[L12n508(0,0)(0,0)]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[L12n520(0,0)(0,0), ribbon_2_14_b82beeeb(0,0)(0,0)]
[L12n544(0,0)(0,0)]
[L12n545(0,0)(0,0)]
[L12n418(0,0)(0,0), ribbon_2_12_b3176713(0,0)(0,0)]
[L14n6154(0,0)(0,0), ribbon_2_14_19779d66(0,0)(0,0)]
[L14n6168(0,0)(0,0), ribbon_2_14_5f88dfaa(0,0)(0,0)]
[L14n6507(0,0)(0,0)]
[L14n6558(0,0)(0,0), ribbon_2_14_b789f3af(0,0)(0,0)]
[L14n6620(0,0)(0,0), ribbon_2_14_3150c2d2(0,0)(0,0)]
[L14n6620(0,0)(0,0), ribbon_2_14_3150c2d2(0,0)(0,0)]
[L14n6832(0,0)(0,0), ribbon_2_14_c3608c49(0,0)(0,0)]
[L14n6985(0,0)(0,0)]
[L14n7118(0,0)(0,0), ribbon_2_14_11f4d7b1(0,0)(0,0)]
[L14n7191(0,0)(0,0)]
[L14n7239(0,0)(0,0), ribbon_2_14_2349a189(0,0)(0,0)]
[L14n7259(0,0)(0,0)]
[L14n6832(0,0)(0,0), ribbon_2_14_c3608c49(0,0)(0,0)]
[L14n7392(0,0)(0,0), ribbon_2_14_698f7d85(0,0)(0,0)]
[L14n7407(0,0)(0,0), ribbon_2_14_d4baebb8(0,0)(0,0)]
[L14n7993(0,0)(0,0)]
[L14n7998(0,0)(0,0)]
[L14n8002(0,0)(0,0)]
[L14n8183(0,0)(0,0), ribbon_2_14_b5ffdf10(0,0)(0,0)]
[L14n8455(0,0)(0,0)]
[L14n8458(0,0)(0,0)]
[L14n8537(0,0)(0,0), ribbon_2_14_a48329e2(0,0)(0,0)]
[L14n8543(0,0)(0,0), ribbon_2_16_30c5bc72(0,0)(0,0)]
[L14n8637(0,0)(0,0)]
[L14n8692(0,0)(0,0)]
[L14n8736(0,0)(0,0), ribbon_2_14_6df01394(0,0)(0,0)]
[L14n8789(0,0)(0,0)]
[L14n8793(0,0)(0,0), ribbon_2_14_b5cb68a0(0,0)(0,0)]
[L14n8803(0,0)(0,0), ribbon_2_14_69184733(0,0)(0,0)]
[L14n8810(0,0)(0,0), ribbon_2_14_8ac3d8b2(0,0)(0,0)]
[L14n8835(0,0)(0,0), ribbon_2_14_a03da83c(0,0)(0,0)]
[L14n7259(0,0)(0,0)]
[L14n9059(0,0)(0,0)]
[L14n9080(0,0)(0,0)]
[L14n8002(0,0)(0,0)]
[L14n9115(0,0)(0,0), ribbon_2_14_65f6cebc(0,0)(0,0)]
[L14n8458(0,0)(0,0)]
[L14n9123(0,0)(0,0)]
[L14n8789(0,0)(0,0)]
[L14n7998(0,0)(0,0)]
[L14n8455(0,0)(0,0)]
[L14n7191(0,0)(0,0)]
[L14n7993(0,0)(0,0)]
[L14n9268(0,0)(0,0)]
[L14n9282(0,0)(0,0)]
[L14n9290(0,0)(0,0)]
[L14n9333(0,0)(0,0)]
[L14n9390(0,0)(0,0)]
[L14n9415(0,0)(0,0)]
[L14n9416(0,0)(0,0)]
[L14n9446(0,0)(0,0)]
[L14n9635(0,0)(0,0)]
[L14n9752(0,0)(0,0)]
[L14n9876(0,0)(0,0)]
[L14n9883(0,0)(0,0)]
[L14n10047(0,0)(0,0)]
[L14n10048(0,0)(0,0)]
[L14n10052(0,0)(0,0)]
[L14n10053(0,0)(0,0)]
[L14n10461(0,0)(0,0)]
[L14n11107(0,0)(0,0)]
[L14n11214(0,0)(0,0)]
[L14n11315(0,0)(0,0)]
[L14n11478(0,0)(0,0)]
[L14n11479(0,0)(0,0)]
[L14n11488(0,0)(0,0)]
[L14n11478(0,0)(0,0)]
[L14n11685(0,0)(0,0)]
[L14n11785(0,0)(0,0)]
[L14n10053(0,0)(0,0)]
[L14n11785(0,0)(0,0)]
[L14n11817(0,0)(0,0)]
[L14n9415(0,0)(0,0)]
[L14n11785(0,0)(0,0)]
[L14n11785(0,0)(0,0)]
[L14n12116(0,0)(0,0)]
[L14n9752(0,0)(0,0)]
[L14n12145(0,0)(0,0), ribbon_2_14_5ae54a40(0,0)(0,0)]
[L14n12364(0,0)(0,0)]
[L14n12414(0,0)(0,0), ribbon_2_14_473214b5(0,0)(0,0)]
[L14n12504(0,0)(0,0), ribbon_2_14_faa25e47(0,0)(0,0)]
[L14n12538(0,0)(0,0), ribbon_2_14_00eb3cdd(0,0)(0,0)]
[L14n12562(0,0)(0,0)]
[L14n12589(0,0)(0,0), ribbon_2_14_25fbc17e(0,0)(0,0)]
[L14n12598(0,0)(0,0), ribbon_2_14_efb17b22(0,0)(0,0)]
[L14n12612(0,0)(0,0)]
[L14n12691(0,0)(0,0)]
[L14n12729(0,0)(0,0)]
[L14n12796(0,0)(0,0)]
[L14n12805(0,0)(0,0)]
[L14n12805(0,0)(0,0)]
[L14n12883(0,0)(0,0)]
[L14n17869(0,0)(0,0), ribbon_2_14_e19560e1(0,0)(0,0)]
[L14n18026(0,0)(0,0)]
[L14n19768(0,0)(0,0), ribbon_2_14_fcf6571a(0,0)(0,0)]
[L14n23729(0,0)(0,0), ribbon_2_14_03c33d52(0,0)(0,0)]
[L14n23784(0,0)(0,0)]
[L14n24046(0,0)(0,0)]
[]
[]
[L14n24461(0,0)(0,0)]
[L14n24652(0,0)(0,0)]
[L14n24914(0,0)(0,0)]
[]
[]
[]
[]
[L14n25100(0,0)(0,0)]
[L14n25175(0,0)(0,0)]
[L14n25286(0,0)(0,0)]
[L14n26023(0,0)(0,0)]
[L14n26057(0,0)(0,0)]
[L14n26105(0,0)(0,0)]
[L14n26107(0,0)(0,0)]
[L14n26149(0,0)(0,0)]
[]
[]
[L14n26301(0,0)(0,0)]
[L14n26677(0,0)(0,0)]
[L14n26301(0,0)(0,0)]
[L14n26908(0,0)(0,0)]
[]
[]
[]
[]
[L14n27343(0,0)(0,0)]
[]
[L14n28013(0,0)(0,0), ribbon_2_14_c23ba356(0,0)(0,0)]
[L14n28016(0,0)(0,0), ribbon_2_14_69b4ddc2(0,0)(0,0)]
[L14n28398(0,0)(0,0)]
[L14n28630(0,0)(0,0), ribbon_2_14_1bc82087(0,0)(0,0)]
[L14n28631(0,0)(0,0), ribbon_2_14_9816b611(0,0)(0,0)]
[L14n28635(0,0)(0,0), ribbon_2_14_be8fa555(0,0)(0,0)]
[]
[]
[L14n28754(0,0)(0,0)]
[L14n28936(0,0)(0,0)]
[L14n29289(0,0)(0,0), ribbon_2_14_c6d975d5(0,0)(0,0)]
[]
[L14n29787(0,0)(0,0)]
[]
[L14n30011(0,0)(0,0), ribbon_2_14_0eb4c90d(0,0)(0,0)]
[L14n30012(0,0)(0,0), ribbon_2_14_9a9f0595(0,0)(0,0)]
[L14n27343(0,0)(0,0)]
[L14n30032(0,0)(0,0)]
[L14n30054(0,0)(0,0)]
[L14n30097(0,0)(0,0), ribbon_2_14_a045cb3a(0,0)(0,0)]
[L14n30103(0,0)(0,0)]
[L14n30103(0,0)(0,0)]
[L14n30108(0,0)(0,0)]
[L14n30116(0,0)(0,0)]
[L14n30127(0,0)(0,0)]
[L14n30128(0,0)(0,0)]
[]
[L14n30250(0,0)(0,0), ribbon_2_14_2f853e82(0,0)(0,0)]
[L14n30442(0,0)(0,0), ribbon_2_14_4f2694ff(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n31090(0,0)(0,0)]
[L14n31138(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n31886(0,0)(0,0)]
[L14n28754(0,0)(0,0)]
[]
[]
[L14n30054(0,0)(0,0)]
[]
[]
[]
[]
[L14n26105(0,0)(0,0)]
[L14n30032(0,0)(0,0)]
[L14n32465(0,0)(0,0)]
[]
[]
[]
[]
[L14n32634(0,0)(0,0)]
[L14n32635(0,0)(0,0)]
[L14n33194(0,0)(0,0)]
[L14n33264(0,0)(0,0)]
[L14n33395(0,0)(0,0), ribbon_2_14_c0b9a7c6(0,0)(0,0)]
[L14n33400(0,0)(0,0), ribbon_2_14_993f5048(0,0)(0,0)]
[L14n33541(0,0)(0,0)]
[L14n33764(0,0)(0,0), ribbon_2_14_1f6a7d1e(0,0)(0,0)]
[L14n33772(0,0)(0,0), ribbon_2_14_bc3e184a(0,0)(0,0)]
[L14n33803(0,0)(0,0)]
[L14n30054(0,0)(0,0)]
[L14n32634(0,0)(0,0)]
[L14n34021(0,0)(0,0)]
[L14n34422(0,0)(0,0)]
[L14n34637(0,0)(0,0), ribbon_2_14_c532d28f(0,0)(0,0)]
[L14n34651(0,0)(0,0)]
[L14n34747(0,0)(0,0)]
[L14n34772(0,0)(0,0)]
[L14n34885(0,0)(0,0)]
[L14n34897(0,0)(0,0)]
[]
[]
[]
[]
[]
[L14n37006(0,0)(0,0)]
[L14n32465(0,0)(0,0)]
[]
[]
[L14n37664(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n38233(0,0)(0,0)]
[L14n33194(0,0)(0,0)]
[L14n30054(0,0)(0,0)]
[L14n38362(0,0)(0,0), ribbon_2_14_699ce1bc(0,0)(0,0)]
[L14n38364(0,0)(0,0), ribbon_2_14_34a1a2a4(0,0)(0,0)]
[L14n38403(0,0)(0,0)]
[L14n38409(0,0)(0,0), ribbon_2_14_964201ff(0,0)(0,0)]
[L14n38410(0,0)(0,0)]
[L14n38511(0,0)(0,0)]
[L14n38511(0,0)(0,0)]
[L14n38799(0,0)(0,0)]
[L14n38799(0,0)(0,0)]
[L14n38901(0,0)(0,0)]
[L14n38932(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n39091(0,0)(0,0)]
[]
[]
[L14n39113(0,0)(0,0)]
[L14n39200(0,0)(0,0)]
[L14n39205(0,0)(0,0)]
[L14n39205(0,0)(0,0)]
[L14n39222(0,0)(0,0)]
[L14n39252(0,0)(0,0)]
[L14n39282(0,0)(0,0)]
[]
[]
[L14n39366(0,0)(0,0)]
[L14n39377(0,0)(0,0)]
[L14n39390(0,0)(0,0)]
[L14n39451(0,0)(0,0)]
[L14n39497(0,0)(0,0)]
[L14n39517(0,0)(0,0)]
[L14n39497(0,0)(0,0)]
[L14n39525(0,0)(0,0)]
[L14n39624(0,0)(0,0)]
[L14n39802(0,0)(0,0)]
[L14n39804(0,0)(0,0)]
[L14n39807(0,0)(0,0)]
[L14n39822(0,0)(0,0)]
[L14n39871(0,0)(0,0)]
[L14n39896(0,0)(0,0)]
[L14n38233(0,0)(0,0)]
[]
[]
[L14n39802(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[L13n5341(0,0)(0,0)]
[L14n40047(0,0)(0,0)]
[L14n45824(0,0)(0,0)(0,0)]
[L14n45834(0,0)(0,0)(0,0)]
[L14n47161(0,0)(0,0)(0,0)]
[]
[]
[L14n47685(0,0)(0,0)(0,0)]
[L14n47721(0,0)(0,0)(0,0)]
[L14n47748(0,0)(0,0)(0,0)]
[L14n47755(0,0)(0,0)(0,0)]
[L14n47771(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L13n8458(0,0)(0,0)(0,0)]
[L12n1829(0,0)(0,0)(0,0)]
[L14n47748(0,0)(0,0)(0,0)]
[L14n47748(0,0)(0,0)(0,0)]
[L14n47755(0,0)(0,0)(0,0)]
[L14n47755(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[L14n48185(0,0)(0,0)(0,0)]
[]
[L14n48333(0,0)(0,0)(0,0)]
[L14n48368(0,0)(0,0)(0,0)]
[L14n45834(0,0)(0,0)(0,0)]
[L14n45824(0,0)(0,0)(0,0)]
[L14n47161(0,0)(0,0)(0,0)]
[L14n48404(0,0)(0,0)(0,0)]
[L14n48413(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[L14n48699(0,0)(0,0)(0,0)]
[]
[]
[]
[L14n48798(0,0)(0,0)(0,0)]
[]
[L12n1755(0,0)(0,0)(0,0)]
[L14n49746(0,0)(0,0)(0,0)]
[L14n50034(0,0)(0,0)(0,0)]
[L14n49746(0,0)(0,0)(0,0)]
[L14n50271(0,0)(0,0)(0,0)]
[L14n48699(0,0)(0,0)(0,0)]
[L14n50508(0,0)(0,0)(0,0)]
[L14n50513(0,0)(0,0)(0,0)]
[L14n50866(0,0)(0,0)(0,0)]
[L14n50867(0,0)(0,0)(0,0)]
[L12n1755(0,0)(0,0)(0,0)]
[L14n51401(0,0)(0,0)(0,0)]
[]
[]
[L14n51499(0,0)(0,0)(0,0)]
[]
[]
[]
[L12n1829(0,0)(0,0)(0,0)]
[L12n1829(0,0)(0,0)(0,0)]
[L12n1755(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[L14n51776(0,0)(0,0)(0,0)]
[]
[L14n51828(0,0)(0,0)(0,0)]
[L14n51839(0,0)(0,0)(0,0)]
[L14n51892(0,0)(0,0)(0,0)]
[]
[L14n51946(0,0)(0,0)(0,0)]
[L14n51499(0,0)(0,0)(0,0)]
[L14n51997(0,0)(0,0)(0,0)]
[L14n52016(0,0)(0,0)(0,0)]
[L14n52050(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n52172(0,0)(0,0)(0,0)]
[L14n52189(0,0)(0,0)(0,0)]
[L14n52190(0,0)(0,0)(0,0)]
[L14n51776(0,0)(0,0)(0,0)]
[L14n52189(0,0)(0,0)(0,0)]
[L14n52190(0,0)(0,0)(0,0)]
[L14n51997(0,0)(0,0)(0,0)]
[L14n51828(0,0)(0,0)(0,0)]
[L14n51946(0,0)(0,0)(0,0)]
[L14n50508(0,0)(0,0)(0,0)]
[L14n50513(0,0)(0,0)(0,0)]
[L14n52050(0,0)(0,0)(0,0)]
[L14n51839(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n52753(0,0)(0,0)(0,0)]
[L14n52846(0,0)(0,0)(0,0)]
[]
[]
[L14n52933(0,0)(0,0)(0,0)]
[]
[]
[L14n52998(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[]
[L14n52846(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[L14n52933(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[]
[]
[]
[L14n58511(0,0)(0,0)(0,0)]
[]
[]
[]
[]
[L14n58759(0,0)(0,0)(0,0)]
[]
[L14n59991(0,0)(0,0)(0,0)(0,0)]
[]
[]
[L14n62346(0,0)(0,0)(0,0)(0,0)]
[L14n62356(0,0)(0,0)(0,0)(0,0), ooct06_05767(0,0)(0,0)(0,0)(0,0)]
[]
[L14n62588(0,0)(0,0)(0,0)(0,0)]
[]
[L14n62717(0,0)(0,0)(0,0)(0,0)]
[]
[]
73 known ribbon links in snappy database
checked for jones determinants, 444 potential ribbon links
df columns after check_products Index(['name_unoriented', 'determinant', 'num_crossings', 'matrix_zero',
       'components', 'jones_factorable', 'jones_determinant', 'known_ribbon',
       'has_unknot', 'mod32_condition'],
      dtype='object')
checked for mod 32, 192 potential ribbon links, 72 known ribbons among them
checked for mod 8 165 potential ribbon links
True
True
False
False
False
True
True
True
True
True
True
True
True
True
False
False
True
False
False
True
True
True
True
True
True
True
True
False
False
True
False
False
True
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
False
False
False
True
False
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
False
False
False
False
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
False
True
False
False
False
False
False
True
True
True
True
False
True
False
True
False
False
False
False
True
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
True
True
True
True
applied fox milnor condition, 94 potential ribbon links

In [3]:
!sage  "../sage_script/check_ribbon_census.sage"

[t12054(0,0)(0,0), 10^2_26(0,0)(0,0), L10n32(0,0)(0,0), ooct02_00007(0,0)(0,0), ribbon_2_10_dc42cb6a(0,0)(0,0)]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[L12n399(0,0)(0,0), ribbon_2_12_f96042d9(0,0)(0,0)]
[L12n418(0,0)(0,0), ribbon_2_12_b3176713(0,0)(0,0)]
[L12n520(0,0)(0,0), ribbon_2_14_b82beeeb(0,0)(0,0)]
[L12n529(0,0)(0,0), ribbon_2_12_2522b6b3(0,0)(0,0)]
[L12n817(0,0)(0,0)]
[L12n910(0,0)(0,0), ribbon_2_12_c8af5edd(0,0)(0,0)]
[L12n1180(0,0)(0,0), ribbon_2_12_82049773(0,0)(0,0)]
[L12n1181(0,0)(0,0), ribbon_2_12_318a1895(0,0)(0,0)]
[L12n1327(0,0)(0,0), ribbon_2_12_4118336d(0,0)(0,0)]
[t12054(0,0)(0,0), 10^2_26(0,0)(0,0), L10n32(0,0)(0,0), ooct02_00007(0,0)(0,0), ribbon_2_10_dc42cb6a(0,0)(0,0)]
[L13n754(0,0)(0,0), ribbon_2_13_cd58ecfd(0,0)(0,0)]
[L13n759(0,0)(0,0), ribbon_2_13_2b1abc12(0,0)(0,0)]
[L13n760(0,0)(0,0), ribbon_2_13_fc552163(0,0)(0,0)]
[L13n1488(0,0)(0,0), ribbon_2_13_95cfb058(0,0)(0,0)]
[L13n1494(0,0)(0,0), ribbon_2_13_e1b3f674(0,0)(0,0)]
[L13n1704(0,0)(0,0), ribbon_2_13_5a6ca7d0(0,0)(0,0)]
[L13n1707(0,0)(0,0), ribbon_2_13_82f84b7d(0,0)(0,0)]
[L13n2407(0,0)(0,0)]
[L13n3056(0,0)(0,0), ribbon_2_13_5d43499e(0,0)(0,0)]
[]
[L12n529(0,0)(0,0), ribbon_2_12_2522b6b3(0,0)(0,0)]
[t12052(0,0)(0,0), 10^2_104(0,0)(0,0), L10n36(0,0)(0,0), ooct02_00006(0,0)(0,0), ribbon_2_10_7ecd0dc0(0,0)(0,0)]
[L12n520(0,0)(0,0), ribbon_2_14_b82beeeb(0,0)(0,0)]
[L12n418(0,0)(0,0), ribbon_2_12_b3176713(0,0)(0,0)]
[L14n6154(0,0)(0,0), ribbon_2_14_19779d66(0,0)(0,0)]
[L14n6168(0,0)(0,0), ribbon_2_14_5f88dfaa(0,0)(0,0)]
[L14n6558(0,0)(0,0), ribbon_2_14_b789f3af(0,0)(0,0)]
[L14n6620(0,0)(0,0), ribbon_2_14_3150c2d2(0,0)(0,0)]
[L14n6620(0,0)(0,0), ribbon_2_14_3150c2d2(0,0)(0,0)]
[L14n6832(0,0)(0,0), ribbon_2_14_c3608c49(0,0)(0,0)]
[L14n7118(0,0)(0,0), ribbon_2_14_11f4d7b1(0,0)(0,0)]
[L14n7239(0,0)(0,0), ribbon_2_14_2349a189(0,0)(0,0)]
[L14n6832(0,0)(0,0), ribbon_2_14_c3608c49(0,0)(0,0)]
[L14n7392(0,0)(0,0), ribbon_2_14_698f7d85(0,0)(0,0)]
[L14n7407(0,0)(0,0), ribbon_2_14_d4baebb8(0,0)(0,0)]
[L14n8183(0,0)(0,0), ribbon_2_14_b5ffdf10(0,0)(0,0)]
[L14n8537(0,0)(0,0), ribbon_2_14_a48329e2(0,0)(0,0)]
[L14n8543(0,0)(0,0), ribbon_2_16_30c5bc72(0,0)(0,0)]
[L14n8736(0,0)(0,0), ribbon_2_14_6df01394(0,0)(0,0)]
[L14n8793(0,0)(0,0), ribbon_2_14_b5cb68a0(0,0)(0,0)]
[L14n8803(0,0)(0,0), ribbon_2_14_69184733(0,0)(0,0)]
[L14n8810(0,0)(0,0), ribbon_2_14_8ac3d8b2(0,0)(0,0)]
[L14n8835(0,0)(0,0), ribbon_2_14_a03da83c(0,0)(0,0)]
[L14n9080(0,0)(0,0)]
[L14n9115(0,0)(0,0), ribbon_2_14_65f6cebc(0,0)(0,0)]
[L14n12145(0,0)(0,0), ribbon_2_14_5ae54a40(0,0)(0,0)]
[L14n12414(0,0)(0,0), ribbon_2_14_473214b5(0,0)(0,0)]
[L14n12504(0,0)(0,0), ribbon_2_14_faa25e47(0,0)(0,0)]
[L14n12538(0,0)(0,0), ribbon_2_14_00eb3cdd(0,0)(0,0)]
[L14n12589(0,0)(0,0), ribbon_2_14_25fbc17e(0,0)(0,0)]
[L14n12598(0,0)(0,0), ribbon_2_14_efb17b22(0,0)(0,0)]
[L14n12691(0,0)(0,0)]
[L14n12729(0,0)(0,0)]
[L14n12796(0,0)(0,0)]
[L14n12805(0,0)(0,0)]
[L14n12805(0,0)(0,0)]
[L14n12883(0,0)(0,0)]
[L14n17869(0,0)(0,0), ribbon_2_14_e19560e1(0,0)(0,0)]
[L14n18026(0,0)(0,0)]
[L14n19768(0,0)(0,0), ribbon_2_14_fcf6571a(0,0)(0,0)]
[L14n23729(0,0)(0,0), ribbon_2_14_03c33d52(0,0)(0,0)]
[L14n28013(0,0)(0,0), ribbon_2_14_c23ba356(0,0)(0,0)]
[L14n28016(0,0)(0,0), ribbon_2_14_69b4ddc2(0,0)(0,0)]
[L14n28630(0,0)(0,0), ribbon_2_14_1bc82087(0,0)(0,0)]
[L14n28631(0,0)(0,0), ribbon_2_14_9816b611(0,0)(0,0)]
[L14n28635(0,0)(0,0), ribbon_2_14_be8fa555(0,0)(0,0)]
[L14n29289(0,0)(0,0), ribbon_2_14_c6d975d5(0,0)(0,0)]
[L14n30011(0,0)(0,0), ribbon_2_14_0eb4c90d(0,0)(0,0)]
[L14n30012(0,0)(0,0), ribbon_2_14_9a9f0595(0,0)(0,0)]
[L14n30097(0,0)(0,0), ribbon_2_14_a045cb3a(0,0)(0,0)]
[L14n30103(0,0)(0,0)]
[L14n30103(0,0)(0,0)]
[L14n30116(0,0)(0,0)]
[L14n30250(0,0)(0,0), ribbon_2_14_2f853e82(0,0)(0,0)]
[L14n30442(0,0)(0,0), ribbon_2_14_4f2694ff(0,0)(0,0)]
[]
[L14n33395(0,0)(0,0), ribbon_2_14_c0b9a7c6(0,0)(0,0)]
[L14n33400(0,0)(0,0), ribbon_2_14_993f5048(0,0)(0,0)]
[L14n33764(0,0)(0,0), ribbon_2_14_1f6a7d1e(0,0)(0,0)]
[L14n33772(0,0)(0,0), ribbon_2_14_bc3e184a(0,0)(0,0)]
[L14n34637(0,0)(0,0), ribbon_2_14_c532d28f(0,0)(0,0)]
[]
[L14n38362(0,0)(0,0), ribbon_2_14_699ce1bc(0,0)(0,0)]
[L14n38364(0,0)(0,0), ribbon_2_14_34a1a2a4(0,0)(0,0)]
[L14n38409(0,0)(0,0), ribbon_2_14_964201ff(0,0)(0,0)]
[L14n38410(0,0)(0,0)]
[]
[]
[]
[]
[]

In [4]:
result= pd.read_csv('/Users/seohyeonlee/knotinfo/results/checked_against_ribbon_census.csv')
result.shape

unverified_candidates = result[result['known_ribbon'] == False]

result[result['known_ribbon']].shape


known_ribbons = result[result['known_ribbon']]

In [ ]:
known_ribbons = known_ribbons['name_unoriented'].tolist()


for item in

['L10n32',
 'L10n36',
 'L12n84',
 'L12n399',
 'L12n418',
 'L12n520',
 'L12n529',
 'L12n910',
 'L12n1180',
 'L12n1181',
 'L12n1327',
 'L13n118',
 'L13n754',
 'L13n759',
 'L13n760',
 'L13n1488',
 'L13n1494',
 'L13n1704',
 'L13n1707',
 'L13n3056',
 'L14n756',
 'L14n1004',
 'L14n1449',
 'L14n1639',
 'L14n6154',
 'L14n6168',
 'L14n6558',
 'L14n6620',
 'L14n6789',
 'L14n6832',
 'L14n7118',
 'L14n7239',
 'L14n7360',
 'L14n7392',
 'L14n7407',
 'L14n8183',
 'L14n8537',
 'L14n8543',
 'L14n8736',
 'L14n8793',
 'L14n8803',
 'L14n8810',
 'L14n8835',
 'L14n9115',
 'L14n12145',
 'L14n12414',
 'L14n12504',
 'L14n12538',
 'L14n12589',
 'L14n12598',
 'L14n17869',
 'L14n19768',
 'L14n23729',
 'L14n28013',
 'L14n28016',
 'L14n28630',
 'L14n28631',
 'L14n28635',
 'L14n29289',
 'L14n30011',
 'L14n30012',
 'L14n30097',
 'L14n30250',
 'L14n30442',
 'L14n33395',
 'L14n33400',
 'L14n33764',
 'L14n33772',
 'L14n34637',
 'L14n38362',
 'L14n38364',
 'L14n38409']

In [ ]:
!sage  "../sage_script/calculate_ribbon_number.sage"

Traceback (most recent call last):
  File "/Users/seohyeonlee/knotinfo/exploration/../sage_script/calculate_ribbon_number.sage.py", line 34, in <module>
    known_ribbons_with_bounds = known_ribbons.apply(lambda row: calculate_ribbon_number(row), axis=_sage_const_1 )
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seohyeonlee/Library/SageMath-10-6/lib/python3.12/site-packages/pandas/core/frame.py", line 10381, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/Users/seohyeonlee/Library/SageMath-10-6/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seohyeonlee/Library/SageMath-10-6/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seohyeonlee/Library/SageMath-10-6/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seohyeonlee/knotinfo/exploration/../sage_script/calculate_ribbon_number.sage.py", line 34, in <lambda>
    known_ribbons_with_bounds = known_ribbons.apply(lambda row: calculate_ribbon_number(row), axis=_sage_const_1 )
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seohyeonlee/knotinfo/exploration/../sage_script/calculate_ribbon_number.sage.py", line 21, in calculate_ribbon_number
    det =  alex_poly(q=-_sage_const_1 )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable

In [6]:
unverified_candidates['name_unoriented'].dtype

dtype('O')

In [20]:
#add L13n10.. as an entry

#list of links verified using symmetric presentation
#
lst = 'L12n418,L12n520,L13n1488,L13n1494,L14n6154,L14n6832,L14n7239,L14n7392,L14n8183,L14n8537,L14n8810,L14n12414,L12n1327,L14n28016,L12n84,L13n118,L14n1004,L12n529,L12n399,L14n756,L14n6832,L14n6168'
lst = lst.split(',')
verified = lst

print(verified)


def sym_found(row):
	linkname = str(row['name_unoriented'])
	return linkname in verified

result['symmetric_presentation_found'] = result.apply(sym_found, axis=1)

['L12n418', 'L12n520', 'L13n1488', 'L13n1494', 'L14n6154', 'L14n6832', 'L14n7239', 'L14n7392', 'L14n8183', 'L14n8537', 'L14n8810', 'L14n12414', 'L12n1327', 'L14n28016', 'L12n84', 'L13n118', 'L14n1004', 'L12n529', 'L12n399', 'L14n756', 'L14n6832', 'L14n6168']

In [ ]:
#all links whose symmetric presentations group k found are already known ribbons so far. can we find symmetric presentations of links that are not verified as ribbons?
result[result['symmetric_presentation_found']]

#need to further verify ribbon-ness

,name_unoriented,determinant,num_crossings,matrix_zero,components,jones_factorable,jones_determinant,known_ribbon,has_unknot,mod32_condition,mod8_condition,fox_milnor_test,symmetric_presentation_found
2,L12n84,0,12,True,2,True,-23,True,True,True,True,True,True
3,L12n399,0,12,True,2,True,-71,True,True,True,True,True,True
4,L12n418,0,12,True,2,True,-71,True,True,True,True,True,True
5,L12n520,0,12,True,2,True,-71,True,True,True,True,True,True
6,L12n529,0,12,True,2,True,-71,True,True,True,True,True,True
11,L12n1327,0,12,True,2,True,-63,True,True,True,True,True,True
12,L13n118,0,13,True,2,True,-23,True,True,True,True,True,True
16,L13n1488,0,13,True,2,True,-143,True,True,True,True,True,True
17,L13n1494,0,13,True,2,True,-143,True,True,True,True,True,True
23,L14n756,0,14,True,2,True,-71,True,True,True,True,True,True
24,L14n1004,0,14,True,2,True,-23,True,True,True,True,True,True
27,L14n6154,0,14,True,2,True,-239,True,True,True,True,True,True
28,L14n6168,0,14,True,2,True,-71,True,True,True,True,True,True
32,L14n6832,0,14,True,2,True,-71,True,True,True,True,True,True
34,L14n7239,0,14,True,2,True,-143,True,True,True,True,True,True
36,L14n7392,0,14,True,2,True,-143,True,True,True,True,True,True
38,L14n8183,0,14,True,2,True,-239,True,True,True,True,True,True
39,L14n8537,0,14,True,2,True,-143,True,True,True,True,True,True
44,L14n8810,0,14,True,2,True,1,True,True,True,True,True,True
49,L14n12414,0,14,True,2,True,-71,True,True,True,True,True,True
65,L14n28016,0,14,True,2,True,-63,True,True,True,True,True,True

In [ ]:


result[~result['known_ribbon']]

,name_unoriented,determinant,num_crossings,matrix_zero,components,jones_factorable,jones_determinant,known_ribbon,has_unknot,mod32_condition,mod8_condition,fox_milnor_test,symmetric_presentation_found
7,L12n817,0,12,True,2,True,-95,False,True,True,True,True,False
20,L13n2407,0,13,True,2,True,-119,False,True,True,True,True,False
22,L13n6537,0,13,True,2,True,-95,False,True,True,True,True,False
46,L14n9080,0,14,True,2,True,-207,False,True,True,True,True,False
54,L14n12691,0,14,True,2,True,-167,False,True,True,True,True,False
55,L14n12729,0,14,True,2,True,-239,False,True,True,True,True,False
56,L14n12796,0,14,True,2,True,-167,False,True,True,True,True,False
57,L14n12805,0,14,True,2,True,-95,False,True,True,True,True,False
58,L14n12876,0,14,True,2,True,-95,False,True,True,True,True,False
59,L14n12883,0,14,True,2,True,-119,False,True,True,True,True,False
61,L14n18026,0,14,True,2,True,-287,False,True,True,True,True,False
73,L14n30103,0,14,True,2,True,-215,False,True,True,True,True,False
74,L14n30107,0,14,True,2,True,-215,False,True,True,True,True,False
75,L14n30116,0,14,True,2,True,-191,False,True,True,True,True,False
78,L14n30755,0,14,True,2,True,9,False,True,True,True,True,False
84,L14n37692,0,14,True,2,True,-159,False,True,True,True,True,False
88,L14n38410,0,14,True,2,True,-287,False,True,True,True,True,False
89,L14n52847,0,14,True,3,True,73,False,True,True,True,True,False
90,L14n52922,0,14,True,3,True,73,False,True,True,True,True,False
91,L14n52934,0,14,True,3,True,73,False,True,True,True,True,False
92,L14n53120,0,14,True,3,True,73,False,True,True,True,True,False
93,L14n53143,0,14,True,3,True,73,False,True,True,True,True,False